# **COPIANDO E EXPLICANDO OS CÓDIGOS COM MINHAS PALAVRAS (Item 1 da Atividade Principal)**

In [ ]:
v <- c(10, 20, 30, 40) # c() = "combine": cria um vetor
v # exibe o vetor
sum(v) # soma os valores do vetor

[1] 10 20 30 40

[1] 100

In [ ]:
notas <- c(ana = 8, bruno = 6, carla = 9) # criação do vetor (vetor númerico nomeado)
notas["bruno"] #exibição do valor vinculado ao nome "bruno"

bruno
    6

In [ ]:
frase <- "recuperacao de informacao" # atribui uma string à variável frase
toupper(frase) # Deixa tudo em maiúsculas
strsplit(frase, " ") #quebra a frase em pedaços, usando espaço como divisor
# quebra em pedacos-> devolve uma LISTA

[1] "RECUPERACAO DE INFORMACAO"

[[1]]
[1] "recuperacao" "de"          "informacao"

In [ ]:
unlist(strsplit(frase, " ")) # unlist achata num vetor simples

[1] "recuperacao" "de"          "informacao"

In [ ]:
dobro <- function(x) { #cria a função
x *2
}
dobro(7) #chama a função e passa 7 como valor

[1] 14

In [ ]:
palavras1 <- list(a = c("x","y","z"), b = c("p","q")) #cria duas listas
lapply(palavras1, length) #mostra a extensão (tamanho) de cada lista. Retorna como lista

$a
[1] 3

$b
[1] 2

In [ ]:
sapply(palavras1, length) #sapply retorna em vetor ou matriz

a b
3 2

In [ ]:
tokens <- c("de", "casa", "de", "rua") #atribui as strings a um vetor chamado "tokens"
table(tokens) #mostra a tabela com a ocorrência de cada elemento

tokens
casa   de  rua
   1    2    1

In [ ]:
vocab <- c("casa", "de", "rua", "praia")
table(factor(tokens, levels = vocab)) # com factor, estabelece levels e reconhece tudo que poderia ser contado,
# mesmo que não exista no vetor tokens

 casa    de   rua praia
    1     2     1     0

In [ ]:
m <- matrix(1:4, nrow = 2) # cria uma matriz, com uma sequência de números de 1 a 4, com um número especifico de linhas
rownames(m) <- c("lin1", "lin2") # nomeia as linhas
colnames(m) <- c("c1", "c2") # aqui, estabelece as colunas
m

     c1 c2
lin1 1  3
lin2 2  4

In [ ]:
peso <- c(2, 3) # atribui à variável "peso" um vetor com 2,3
m * peso # multiplica a matriz: primeiro valor pela primeira linha, segundo valor pela segunda linha

     c1 c2
lin1 2   6
lin2 6  12

In [ ]:
c("casa", "aviao") %in% vocab # verifica se cada elemento está no vocab

[1]  TRUE FALSE

In [ ]:
palavras2 <- c("casa", "cachorro", "praia", "cidade") # cria vetor de palavras
grep("^ca", palavras, value = TRUE) # busca quais COMECAM com "ca"
grepl("a$", palavras) # busca quais TERMINAM em "a"
sub("a", "@", "banana") # Troca a PRIMEIRA ocorrência de "a" por "@"
gsub("a", "@", "banana") # Troca TODAS as ocorrências

[1] "casa"     "cachorro"

[1]  TRUE FALSE  TRUE FALSE

[1] "b@nana"

[1] "b@n@n@"

# **ALTERANDO E ANTECIPANDO O RESULTADO PARA TESTAR (Itens 2 e 3  da tarefa principal) **

In [ ]:

pesonovo <- c(2, 3, 4) # alterei aqui o vetor, acrescentando um número para ver como o resultado muda.
# ESPERADO: ou executa ou dá erro
m * pesonovo # Descobri que a operação dá um aviso, porque as extensões são diferentes.
# Então executa, faz a reciclagem, mas dá um aviso. Executa com aviso

Warning message in m * pesonovo:
“longer object length is not a multiple of shorter object length”

     c1 c2
lin1 2  12
lin2 6   8

In [ ]:
mnovo <- matrix(1:6, nrow = 2) #aumentei para 6 os elementos da matriz
rownames(mnovo) <- c("lin1", "lin2") # nomeia as linhas, isso ficou igual
colnames(mnovo) <- c("c1", "c2", "c3") # aqui, estabeleci mais uma coluna
mnovo # ESPERADO: Vai gerar normalmente
#Gerou normalmente

     c1 c2 c3
lin1 1  3  5
lin2 2  4  6

In [ ]:
mnovo * peso # testando matriz nova com peso antigo. #ESPERADO: Vai funcionar, cada valor multiplicará uma linha
# Funciona, cada valor segue multiplicando uma linha

     c1 c2 c3
lin1 2   6 10
lin2 6  12 18

In [ ]:
mnovo * pesonovo # testando com ambos, matriz e peso novos. #ESPERADO: Ou cada valor vai multiplicar uma linha ou vai dar erro
# No caso, o que aconteceu foi a questão da reciclagem.
# O peso novo, como tem 3 elementos e a matriz tem 6 posições, virou como se fosse [2,3,4,2,3,4]
# Aí multiplicou nessa sequência as linhas, cada coluna de cada linha, dando um valor diferente

     c1 c2 c3
lin1 2  12 15
lin2 6   8 24

# **Para casa — parte 2: perguntas para investigar**

In [ ]:
# O que acontece se você trocar sapply por lapply no exemplo? E o contrário?
# sapply(palavras, length)
lapply (palavras1,length)
# Ele em vez de mostrar como vetor ou matriz, mostra como lista. E vice-versa.

$a
[1] 3

$b
[1] 2

In [ ]:
# Em table(factor(tokens, levels = vocab)), o que muda se você remover
# o factor? Por que isso importa para o nosso motor de busca?
table(factor(tokens, levels = vocab)) # (com factor, estabelece levels e reconhece tudo que poderia ser contado)
table((tokens))
#O que vai mudar é que sem o factor, a busca para de pesquisar por levels,
#então para de mostrar termos possível pra busca, mas que retornariam zero nela.

 casa    de   rua praia
    1     2     1     0

casa   de  rua
   1    2    1

In [99]:
# Criando a matriz 2x2 do slide (Slide 13)
m <- matrix(1:4, nrow = 2)
rownames(m) <- c("lin1", "lin2")
colnames(m) <- c("c1", "c2")

# Vetor com 3 elementos
peso3 <- c(2, 3, 5)

# Operação com reciclagem
m * peso3

#Ao multiplicar a matriz 2x2(4 elementos) pelo vetor peso de 3 elementos, o R tentará realizar a reciclagem.
#Como o tamanho da matriz não é um múltiplo do tamanho do vetor, o cálculo será executado elemento a elemento por colunas, mas o R emitirá um warning.
#A reciclagem só ocorre de forma "silenciosa" quando o tamanho do objeto maior é múltiplo do menor (ex: 4 e 2).
#Como 4 não é múltiplo de 3, o R concluiu a última multiplicação reutilizando o primeiro item do vetor, mas emitiu o alerta longer object length is not a multiple of shorter object length para avisar que a reciclagem foi interrompida no meio de um ciclo.

Warning message in m * peso3:
“longer object length is not a multiple of shorter object length”

     c1 c2
lin1 2  15
lin2 6   8

In [100]:
# 1. Criação do vetor nomeado com 3 frases
frases <- c(
  f1 = "recuperacao de informacao e ciencia de dados",
  f2 = "ciencia de dados utiliza processamento de texto",
  f3 = "recuperacao de texto na ciencia de dados"
)

# 2. Tokenização utilizando lapply e quebra por espaços (\s+)
tokens_lista <- lapply(frases, function(texto) {
  unlist(strsplit(texto, "\\s+"))
})

# 3. Transformação em vetor simples (unlist) e contagem dos termos
todos_tokens <- unlist(tokens_lista)
contagem <- table(todos_tokens)

# 4. Ordenação dos termos do maior para o menor
contagem_ordenada <- sort(contagem, decreasing = TRUE)

# Exibição do resultado
print(contagem_ordenada)

todos_tokens
           de       ciencia         dados   recuperacao         texto
            6             3             3             2             2
            e    informacao            na processamento       utiliza
            1             1             1             1             1

# **5 Missões**

In [98]:
manchetes <- c(
"Porto de Santos bate recorde em julho - A Tribuna",
"cubatao registra melhora na qualidade do ar - A Tribuna",
"Guaruja tera nova linha de onibus em 2026 - A Tribuna",
"Sao Vicente inaugura escola no Parque Bitaru - A Tribuna",
"Santos e Guaruja discutem travessia de balsa - A Tribuna"
)

#1- Faxina:
print("Manchetes sem 'a tribuna'")
frases_limpas <- sub(" - A Tribuna$", "", manchetes)
frases_limpas

#2- Espaços:
print("Mudando dois ou mais espaços por um")
gsub("\\s{2,}", " ", frases_limpas)

#3- Ano:
print("Quais manchetes citam um ano (4 digitos)")
grep("[0-9]{4}", frases_limpas, value= TRUE)

#4- Municípios:
print("Quais manchetes citam Guarujá ou Cubatão, ignorando maiúsculas")
grep("Guaruja|Cubatao", frases_limpas, ignore.case = TRUE, value = TRUE)

#5- A pegadinha:
print("Com ''grepl('Santos', manchetes)'' acha 2 manchetes — mas uma
fala do Porto, não da cidade. Como você distinguiria? É possível só com regex?")
grepl("Santos", frases_limpas)
print("Seria possível remover a palavra porto da pesquisa com regex, porém com uma quantidade maior
de manchetes poderia ocorrer um erro... A regex reconhece apenas padrões de texto, não o significado
das palavras, então não distingui a utilização da palavra 'Santos'")

[1] "Manchetes sem 'a tribuna'"

[1] "Porto de Santos bate recorde em julho"
[2] "cubatao registra melhora na qualidade do ar"
[3] "Guaruja tera nova linha de onibus em 2026"
[4] "Sao Vicente inaugura escola no Parque Bitaru"
[5] "Santos e Guaruja discutem travessia de balsa"

[1] "Mudando dois ou mais espaços por um"

[1] "Porto de Santos bate recorde em julho"
[2] "cubatao registra melhora na qualidade do ar"
[3] "Guaruja tera nova linha de onibus em 2026"
[4] "Sao Vicente inaugura escola no Parque Bitaru"
[5] "Santos e Guaruja discutem travessia de balsa"

[1] "Quais manchetes citam um ano (4 digitos)"

[1] "Guaruja tera nova linha de onibus em 2026"

[1] "Quais manchetes citam Guarujá ou Cubatão, ignorando maiúsculas"

[1] "cubatao registra melhora na qualidade do ar"
[2] "Guaruja tera nova linha de onibus em 2026"
[3] "Santos e Guaruja discutem travessia de balsa"

[1] "Com ''grepl('Santos', manchetes)'' acha 2 manchetes — mas uma\nfala do Porto, não da cidade. Como você distinguiria? É possível só com regex?"

[1]  TRUE FALSE FALSE FALSE  TRUE

[1] "Seria possível remover a palavra porto da pesquisa com regex, porém com uma quantidade maior\nde manchetes poderia ocorrer um erro... A regex reconhece apenas padrões de texto, não o significado\ndas palavras, então não distingui a utilização da palavra 'Santos'"